modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://example.invalid/testdimension/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayTest="IGNORE_SERVER_VERSION"
authors="${mod_authors}"
description='''${mod_description}'''

[features.${mod_id}]
javaVersion="[21,)"

[[accessTransformers]]
file="META-INF/testdimperm.cfg"

[[mixins]]
config="mixins.testdimensions.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
